apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8081
      nodePort: {{ .Values.service.nodePort }}	
