apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: server-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-app
  data:
  - secretKey: server_service_ip
    remoteRef:
      key: details
      property: server_service_ip
