apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: "http://{{ .Values.secretStore.vaultIP }}:8200"
      path: app
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
