apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.storage }}
