apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: mongodb-pod  
        image: mongo
        ports:
        - containerPort: 27017
#        env: 
#        - name: MONGO_INITDB_ROOT_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: mongo-root-username		  
#        - name: MONGO_INITDB_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mongodb-secret
#              key: mongo-root-password 
        volumeMounts:
          - mountPath: /data/db
            name: mo-data
      volumes:
      - name: mo-data
        persistentVolumeClaim:
          claimName: {{ .Values.PersistentVolumeClaim.name }}
