apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: server-pod  
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_MONGODB_IP 
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: mongodb_ip
