apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.service.targetPort }}
