# Default values for server.

namespace: shir2

labels:
  app: server

image:
  repository: paasshir2/server
  tag: 0.8

service:
  targetPort: 3000
  externalIP2: 20.93.43.135
  externalIP: MjAuOTMuNDMuMTM1

secretStore:
  vaultIP: 20.223.44.64
